check input

diff --git a/build-element b/build-element
--- a/build-element
+++ b/build-element
@@ -13,6 +13,21 @@ FEDORA_VER="$1"
 MAJOR="$(echo $2 | awk -F '.' '{ print $1"."$2}')"
 MINOR="$(echo $2 | awk -F '.' '{ print $3}')"
 
+if test -z $FEDORA_VER; then
+    echo "Fedora version missing"
+    exit 1
+fi
+
+if test -z $MAJOR; then
+    echo "Element major version missing"
+    exit 1
+fi
+
+if test -z $MINOR; then
+    echo "Element minor version missing"
+    exit 1
+fi
+
 ELEMENT_VER="${MAJOR}.${MINOR}"
 echo "Building element: $ELEMENT_VER on $FEDORA_VER"
 
